defaults:
  - module: regression
  - datamodule: atp_datamodule
  - callbacks:
    - early_stopping
    - learning_rate_monitor
    - model_checkpoint
  - _self_

name: null
log_dir: logs/

datamodule:
  preprocessors:
    - _target_: atp.preprocess.NormByCompound

trainer:
  max_epochs: 150
  seed: 42
  accumulate_grad_batches: 1
  monitor: val_loss
  accelerator: cpu
  devices: 1